### ISSUE TITLE
Regarding aioquic issue 72

### ISSUE THREAD

**Issue by devkdas** [honglei/jquery_params#1]
hai ,

It is not an issue.
one small quick query

@honglei 
Could you please send me the code or file which you have written to run all the aioquic unittest's in a single step.

Issue 72 link
https://github.com/aiortc/aioquic/issues/72

Sorry for raising an issue to ask this query.

Looking forward for your reply

Thank you.

**Comment by honglei** [comment]
Just  run `pytest` in the project code,   u can use actions to do test,like
https://github.com/aiortc/aioquic/actions/runs/2688528322/workflow

```test
      - name: Run tests
        run: |
          python -m pip install -U pip setuptools wheel
          pip install coverage
          pip install .
          coverage run -m unittest discover -v
          coverage xml
        shell: bash
```

**Comment by devkdas** [comment]
Thank you for replying back @honglei and for you help.
